#pragma once

typedef enum {
  ENKI_ERROR_OK = 0,
  ENKI_ERROR_BAD_PIN = 1,
  ENKI_ERROR_TYPE = 2,
  ENKI_ERROR_DIV_ZERO = 3,
  ENKI_ERROR_OOM = 4,
  ENKI_ERROR_BOUNDS = 5,
  ENKI_ERROR_BAD_TAG = 6,
  ENKI_ERROR_THROW = 7,
  ENKI_STORE_NOT_FOUND = 8,
  ENKI_STORE_TOO_SMALL = 9,
  ENKI_STORE_ERROR = 10,
} enki_error;
