#pragma once

typedef enum {
    ENKI_ERROR_OK,
    ENKI_ERROR_BAD_PIN,
    ENKI_ERROR_TYPE,
    ENKI_ERROR_DIV_ZERO,
    ENKI_ERROR_OOM,
    ENKI_ERROR_BOUNDS,
    ENKI_ERROR_BAD_TAG,
    ENKI_ERROR_THROW,
    ENKI_STORE_NOT_FOUND,
    ENKI_STORE_TOO_SMALL,
    ENKI_STORE_ERROR,
} enki_error;
