#pragma once

#include <stddef.h>
#include <stdint.h>

#include "enki/interp.h"
#include "enki/value.h"
#include "enki/vector.h"

typedef enum {
    PRIM_PIN,
    PRIM_LAW,
    PRIM_ELIM,
    PRIM_INC,
    PRIM_DEC,
    PRIM_ADD,
    PRIM_SUB,
    PRIM_MUL,
    PRIM_DIV,
    PRIM_MOD,
    PRIM_EQ,
    PRIM_NE,
    PRIM_LT,
    PRIM_LE,
    PRIM_GT,
    PRIM_GE,
    PRIM_CMP,
    PRIM_RSH,
    PRIM_LSH,
    PRIM_TEST,
    PRIM_SET,
    PRIM_CLEAR,
    PRIM_BEX,
    PRIM_BITS,
    PRIM_BYTES,
    PRIM_NIB,
    PRIM_LOAD8,
    PRIM_STORE8,
    PRIM_TRUNC,
    PRIM_TRUNC8,
    PRIM_TRUNC16,
    PRIM_TRUNC32,
    PRIM_TRUNC64,
    PRIM_TYPE,
    PRIM_IS_PIN,
    PRIM_IS_LAW,
    PRIM_IS_APP,
    PRIM_IS_NAT,
    PRIM_NAT,
    PRIM_UNPIN,
    PRIM_ARITY,
    PRIM_NAME,
    PRIM_BODY,
    PRIM_HD,
    PRIM_LAST,
    PRIM_INIT,
    PRIM_ROW,
    PRIM_REP,
    PRIM_SLICE,
    PRIM_WELD,
    PRIM_UP,
    PRIM_UP_UNIQ,
    PRIM_COUP,
    PRIM_SZ,
    PRIM_IX,
    PRIM_IX0,
    PRIM_IX1,
    PRIM_IX2,
    PRIM_IX3,
    PRIM_IX4,
    PRIM_IX5,
    PRIM_IX6,
    PRIM_IX7,
    PRIM_CASE,
    PRIM_CASE2,
    PRIM_CASE3,
    PRIM_CASE4,
    PRIM_CASE5,
    PRIM_CASE6,
    PRIM_CASE7,
    PRIM_CASE8,
    PRIM_CASE9,
    PRIM_CASE10,
    PRIM_CASE11,
    PRIM_CASE12,
    PRIM_CASE13,
    PRIM_CASE14,
    PRIM_CASE15,
    PRIM_CASE16,
    PRIM_NIL,
    PRIM_TRUTH,
    PRIM_OR,
    PRIM_NOR,
    PRIM_AND,
    PRIM_IF,
    PRIM_IFZ,
    PRIM_SEQ,
    PRIM_SEQ2,
    PRIM_SEQ3,
    PRIM_SAP,
    PRIM_SAP2,
    PRIM_FORCE,
    PRIM_DEEPSEQ,
    PRIM_TRY,
    PRIM_THROW,
    PRIM_SAVE,
    PRIM_LOAD,
    PRIM_TRACE,
    PRIM_EQUAL,
    PRIM_PARSE_REX,
    PRIM_PRINT_REX,
    PRIM_COUNT,
} enki_prim_id;

typedef struct {
    enki_prim_id id;
    uint8_t group;
    uint8_t subop_b;
    uint8_t arity_s;
} enki_prim_spec;


#define MAX_PRIM_ID ((enki_value)(PRIM_COUNT - 1))
static const enki_prim_spec ENKI_PRIMS[] = {
    { PRIM_PIN,        OP_OP0,  OP0_PIN,        1 },
    { PRIM_LAW,        OP_OP0,  OP0_LAW,        3 },
    { PRIM_ELIM,       OP_OP0,  OP0_ELIM,       6 },

    { PRIM_INC,        OP_OP66, OP66_INC,       1 },
    { PRIM_DEC,        OP_OP66, OP66_DEC,       1 },
    { PRIM_ADD,        OP_OP66, OP66_ADD,       2 },
    { PRIM_SUB,        OP_OP66, OP66_SUB,       2 },
    { PRIM_MUL,        OP_OP66, OP66_MUL,       2 },
    { PRIM_DIV,        OP_OP66, OP66_DIV,       2 },
    { PRIM_MOD,        OP_OP66, OP66_MOD,       2 },

    { PRIM_EQ,         OP_OP66, OP66_EQ,        2 },
    { PRIM_NE,         OP_OP66, OP66_NE,        2 },
    { PRIM_LT,         OP_OP66, OP66_LT,        2 },
    { PRIM_LE,         OP_OP66, OP66_LE,        2 },
    { PRIM_GT,         OP_OP66, OP66_GT,        2 },
    { PRIM_GE,         OP_OP66, OP66_GE,        2 },
    { PRIM_CMP,        OP_OP66, OP66_CMP,       2 },

    { PRIM_RSH,        OP_OP66, OP66_RSH,       2 },
    { PRIM_LSH,        OP_OP66, OP66_LSH,       2 },
    { PRIM_TEST,       OP_OP66, OP66_TEST,      2 },
    { PRIM_SET,        OP_OP66, OP66_SET,       2 },
    { PRIM_CLEAR,      OP_OP66, OP66_CLEAR,     2 },
    { PRIM_BEX,        OP_OP66, OP66_BEX,       1 },
    { PRIM_BITS,       OP_OP66, OP66_BITS,      1 },
    { PRIM_BYTES,      OP_OP66, OP66_BYTES,     1 },
    { PRIM_NIB,        OP_OP66, OP66_NIB,       2 },
    { PRIM_LOAD8,      OP_OP66, OP66_LOAD8,     2 },
    { PRIM_STORE8,     OP_OP66, OP66_STORE8,    3 },
    { PRIM_TRUNC,      OP_OP66, OP66_TRUNC,     2 },
    { PRIM_TRUNC8,     OP_OP66, OP66_TRUNC8,    1 },
    { PRIM_TRUNC16,    OP_OP66, OP66_TRUNC16,   1 },
    { PRIM_TRUNC32,    OP_OP66, OP66_TRUNC32,   1 },
    { PRIM_TRUNC64,    OP_OP66, OP66_TRUNC64,   1 },

    { PRIM_TYPE,       OP_OP66, OP66_TYPE,      1 },
    { PRIM_IS_PIN,     OP_OP66, OP66_IS_PIN,    1 },
    { PRIM_IS_LAW,     OP_OP66, OP66_IS_LAW,    1 },
    { PRIM_IS_APP,     OP_OP66, OP66_IS_APP,    1 },
    { PRIM_IS_NAT,     OP_OP66, OP66_IS_NAT,    1 },
    { PRIM_NAT,        OP_OP66, OP66_NAT,       1 },
    { PRIM_UNPIN,      OP_OP66, OP66_UNPIN,     1 },
    { PRIM_ARITY,      OP_OP66, OP66_ARITY,     1 },
    { PRIM_NAME,       OP_OP66, OP66_NAME,      1 },
    { PRIM_BODY,       OP_OP66, OP66_BODY,      1 },
    { PRIM_HD,         OP_OP66, OP66_HD,        1 },
    { PRIM_LAST,       OP_OP66, OP66_LAST,      1 },
    { PRIM_INIT,       OP_OP66, OP66_INIT,      1 },

    { PRIM_ROW,        OP_OP66, OP66_ROW,       3 },
    { PRIM_REP,        OP_OP66, OP66_REP,       3 },
    { PRIM_SLICE,      OP_OP66, OP66_SLICE,     3 },
    { PRIM_WELD,       OP_OP66, OP66_WELD,      2 },
    { PRIM_UP,         OP_OP66, OP66_UP,        3 },
    { PRIM_UP_UNIQ,    OP_OP66, OP66_UP_UNIQ,   3 },
    { PRIM_COUP,       OP_OP66, OP66_COUP,      2 },
    { PRIM_SZ,         OP_OP66, OP66_SZ,        1 },
    { PRIM_IX,         OP_OP66, OP66_IX,        2 },
    { PRIM_IX0,        OP_OP66, OP66_IX0,       1 },
    { PRIM_IX1,        OP_OP66, OP66_IX1,       1 },
    { PRIM_IX2,        OP_OP66, OP66_IX2,       1 },
    { PRIM_IX3,        OP_OP66, OP66_IX3,       1 },
    { PRIM_IX4,        OP_OP66, OP66_IX4,       1 },
    { PRIM_IX5,        OP_OP66, OP66_IX5,       1 },
    { PRIM_IX6,        OP_OP66, OP66_IX6,       1 },
    { PRIM_IX7,        OP_OP66, OP66_IX7,       1 },

    { PRIM_CASE,       OP_OP66, OP66_CASE,      3 },
    { PRIM_CASE2,      OP_OP66, OP66_CASE2,     4 },
    { PRIM_CASE3,      OP_OP66, OP66_CASE3,     5 },
    { PRIM_CASE4,      OP_OP66, OP66_CASE4,     6 },
    { PRIM_CASE5,      OP_OP66, OP66_CASE5,     7 },
    { PRIM_CASE6,      OP_OP66, OP66_CASE6,     8 },
    { PRIM_CASE7,      OP_OP66, OP66_CASE7,     9 },
    { PRIM_CASE8,      OP_OP66, OP66_CASE8,     10 },
    { PRIM_CASE9,      OP_OP66, OP66_CASE9,     11 },
    { PRIM_CASE10,     OP_OP66, OP66_CASE10,    12 },
    { PRIM_CASE11,     OP_OP66, OP66_CASE11,    13 },
    { PRIM_CASE12,     OP_OP66, OP66_CASE12,    14 },
    { PRIM_CASE13,     OP_OP66, OP66_CASE13,    15 },
    { PRIM_CASE14,     OP_OP66, OP66_CASE14,    16 },
    { PRIM_CASE15,     OP_OP66, OP66_CASE15,    17 },
    { PRIM_CASE16,     OP_OP66, OP66_CASE16,    18 },

    { PRIM_NIL,        OP_OP66, OP66_NIL,       1 },
    { PRIM_TRUTH,      OP_OP66, OP66_TRUTH,     1 },
    { PRIM_OR,         OP_OP66, OP66_OR,        2 },
    { PRIM_NOR,        OP_OP66, OP66_NOR,       2 },
    { PRIM_AND,        OP_OP66, OP66_AND,       2 },
    { PRIM_IF,         OP_OP66, OP66_IF,        3 },
    { PRIM_IFZ,        OP_OP66, OP66_IFZ,       3 },

    { PRIM_SEQ,        OP_OP66, OP66_SEQ,       2 },
    { PRIM_SEQ2,       OP_OP66, OP66_SEQ2,      3 },
    { PRIM_SEQ3,       OP_OP66, OP66_SEQ3,      4 },
    { PRIM_SAP,        OP_OP66, OP66_SAP,       2 },
    { PRIM_SAP2,       OP_OP66, OP66_SAP2,      3 },
    { PRIM_FORCE,      OP_OP66, OP66_FORCE,     1 },
    { PRIM_DEEPSEQ,    OP_OP66, OP66_DEEPSEQ,   2 },
    { PRIM_TRY,        OP_OP66, OP66_TRY,       2 },
    { PRIM_THROW,      OP_OP66, OP66_THROW,     1 },

    { PRIM_SAVE,       OP_OP66, OP66_SAVE,      1 },
    { PRIM_LOAD,       OP_OP66, OP66_LOAD,      1 },
    { PRIM_TRACE,      OP_OP66, OP66_TRACE,     2 },
    { PRIM_EQUAL,      OP_OP66, OP66_EQUAL,     2 },
    { PRIM_PARSE_REX,  OP_OP66, OP66_PARSE_REX, 1 },
    { PRIM_PRINT_REX,  OP_OP66, OP66_PRINT_REX, 1 },
};

enki_value enki_law_alloc(enki_gc* gc, size_t arity_s, enki_value name_v, enki_value body_v, 
    size_t bc_len_s, size_t n_const_s, uint8_t* bc_b, enki_value* const_table_v);
void enki_law_compile(enki_interpreter* i, enki_value body_v, size_t arity_s, enki_vector* bc_b, enki_vector* const_table_v);
void enki_law_enter(size_t arity_s, enki_value val_v, enki_interpreter* i);
