name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v14
      - run: nix flake check -L
      - run: nix build -L .#default

  #
  # fuzz-smoke:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: DeterminateSystems/determinate-nix-action@v3
  #     - uses: DeterminateSystems/magic-nix-cache-action@v14
  #     - run: nix run .#fuzz -- -max_total_time=60 -error_exitcode=1

  coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v14
      - run: nix build .#coverage
      - uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./result/enki.info
