name: CI

on:
  push:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake check -L

  #
  # fuzz-smoke:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: cachix/install-nix-action@v31
  #     - uses: DeterminateSystems/magic-nix-cache-action@v8
  #     - run: nix run .#fuzz -- -max_total_time=60 -error_exitcode=1

  coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix build .#coverage
      - uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./result/enki.info

